import { ClerkProvider } from "@clerk/nextjs";
import type { Metadata } from "next";

import { Inter } from "next/font/google";
import "./globals.css";
import { StoreModalProvider } from "@/hooks/ModalContext";
import ModalProvider from "@/components/providers/ModalProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Admin Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <StoreModalProvider>
            <ModalProvider />
            {children}
          </StoreModalProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
