import Footer from "@/components/Footer";
import Header from "@/components/Header";
import { Inter } from "next/font/google";
import "@/app/globals.css";
import Container from "@/components/Container";
import ReactQueryProvider from "@/components/ReactQueryProvider";
import { Toaster } from "react-hot-toast";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "My Posts",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-zinc-100 text-zinc-900`}>
        <Toaster position="top-center" reverseOrder={false} />
        <Container>
          <Header />
          <ReactQueryProvider>
            <main className="container mx-auto">{children}</main>
          </ReactQueryProvider>
          <Footer />
        </Container>
      </body>
    </html>
  );
}
